# Generated by Django 6.0.5 on 2026-06-16 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='employee_id',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{6}$', 'User ID must contain 6 digits.')]),
        ),
    ]
